import type {Metadata} from "next";
import {Inter_Tight} from 'next/font/google'
import Navbar from '@/components/Navbar';
import '@/styles/globals.css';
import {ThemeProvider} from '@/components/ThemeProvider'
import React from "react";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter_tight = Inter_Tight({
    subsets: ['latin'],
    display: 'swap',
})

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={inter_tight.className}>
        <body>

        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <Navbar/>
            <main>{children}</main>
        </ThemeProvider>
        </body>
        </html>
    )
}
